user_pref("_user.js.parrot", "START fromSettings");
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("font.name.serif.x-western", "sans-serif");
user_pref("pocket.enabled", false);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsored", false);
user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.server", "data:=");
user_pref("toolkit.telemetry.unified", false);
user_pref("urlclassifier.features.socialtracking.skipURLs", "*.instagram.com, *.twitter.com, *.x.com, *.twimg.com");
user_pref("urlclassifier.trackingSkipURLs", "*.reddit.com, *.twitter.com, *.x.com, *.twimg.com, *.tiktok.com");
user_pref("_user.js.parrot", "END fromSettings");

user_pref("_user.js.parrot", "START fromPolicies");
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.download.always_ask_before_handling_new_types", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("browser.newtabpage.activity-stream.default.sites", "");
user_pref("browser.newtabpage.activity-stream.feeds.system.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.activity-stream.system.showSponsored", false);
user_pref("browser.pocket.enabled", false);
user_pref("browser.sessionstore.warnOnQuit", true);
user_pref("browser.startup.page", 3);
user_pref("browser.tabs.warnOnClose", true);
user_pref("browser.tabs.warnOnCloseOtherTabs", true);
user_pref("browser.uidensity", 1);
user_pref("browser.warnOnQuit", true);
user_pref("browser.warnOnQuitShortcut", true);
user_pref("extensions.pocket.enabled", false);
user_pref("layout.testing.overlay-scrollbars.always-visible", true);
user_pref("media.autoplay.default", 5);
user_pref("media.autoplay.enabled", false);
user_pref("media.eme.enabled", true);
user_pref("widget.gtk.non-native-titlebar-buttons.enabled", false);
user_pref("widget.gtk.overlay-scrollbars.enabled", false);
user_pref("widget.non-native-theme.gtk.scrollbar.thumb-size", 1);
user_pref("widget.non-native-theme.scrollbar.size.override", 12);
user_pref("_user.js.parrot", "END fromPolicies");
